spring.application.name=ecommerce-service

spring.datasource.url=jdbc:mysql://localhost:3306/ms_ecommerce_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

server.port = 9096

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT CONFIG

#jwt.secret=${JWT_SECRET:mysecurekeymysecurekeymysecurekey123456}
jwt.secret=${JWT_SECRET}
jwt.expiration=3600000

paypal.mode=sandbox
#paypal.client.id=${PAYPAL_CLIENT_ID:ARQbpc1qXlINFi3K6g-VRo0PXELlAgiLslump0u-UYabInrC4r--omI-aCve6Wer6vesCHQpp1Ahniiy}
#paypal.client.secret=${PAYPAL_CLIENT_SECRET:EPFhLjFz7dQ9_IJqNQKQYWhg88Mgg8dNHTrwPinIah4-a3UHj2Ra95kfsocvS1zFOqLvCyrpMPTUou79}

paypal.client.id=${PAYPAL_CLIENT_ID}
paypal.client.secret=${PAYPAL_CLIENT_SECRET}