spring.application.name=authService

spring.datasource.url=jdbc:mysql://localhost:3306/ms_auth_db
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port = 9095

# ✅ JWT Secret (NO hardcoding)
jwt.secret=${JWT_SECRET:mysecurekeymysecurekeymysecurekey123456}
jwt.expiration=3600000